version: '3.9'

services:
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDB;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ASPNETCORE_URLS=http://*:6060 
    networks:
      - backend
    ports:
      - "6061:6060" 

networks:
  backend:
    external: true
